
###################### Package List  #####################

#if(!require("mfx")) { install.packages("mfx") }; library("mfx")
#if(!require("texreg")) { install.packages("texreg") }; library("texreg")
#if(!require("modmarg")) { install.packages("modmarg") }; library("modmarg")
#if(!require("prediction")) { install.packages("prediction") }; library("prediction")
#if(!require("margins")) { install.packages("margins") }; library("margins")
if(!require("ggplot2")) { install.packages("ggplot2") }; library("ggplot2")
if(!require("readxl")) { install.packages("readxl") }; library("readxl")
#if(!require("stargazer")) { install.packages("stargazer") }; library("stargazer")
if(!require("stats")) { install.packages("stats") }; library("stats")
if(!require("Matrix")) { install.packages("Matrix") }; library("Matrix")
if(!require("foreign")) { install.packages("foreign") }; library("foreign")
if(!require("lmtest")) { install.packages("lmtest") }; library("lmtest")
#if(!require("sandwich")) { install.packages("sandwich") }; library("sandwich")
#if(!require("grid")) { install.packages("grid") }; library("grid")
if(!require("dplyr")) { install.packages("dplyr") }; library("dplyr")
if(!require("data.table")) { install.packages("data.table") }; library("data.table")
#if(!require("superheat")) { install.packages("superheat") }; library("superheat")
#if(!require("forcats")) { install.packages("forcats") }; library("forcats")
#if(!require("sampleSelection")) { install.packages("sampleSelection") }; library("sampleSelection")
#if(!require("fastDummies")) { install.packages("fastDummies") }; library("fastDummies")
#if(!require("gridExtra")) { install.packages("gridExtra") }; library("gridExtra")
#if(!require("lattice")) { install.packages("lattice") }; library("lattice")
#if(!require("corrplot")) { install.packages("corrplot") }; library("corrplot")
if(!require("tidyverse")) { install.packages("tidyverse") }; library("tidyverse")
#if(!require("tidytext")) { install.packages("tidytext") }; library("tidytext")
#if(!require("slam")) { install.packages("slam") }; library("slam")
#if(!require("tm")) { install.packages("tm") }; library("tm")
#if(!require("koRpus")) { install.packages("koRpus") }; library("koRpus")
#if(!require("koRpus.lang.en")) { install.packages("koRpus.lang.en") }; library("koRpus.lang.en")
#if(!require("neuralnet")) { install.packages("neuralnet") }; library("neuralnet")
#if(!require("caTools")) { install.packages("caTools") }; library("caTools")
#if(!require("mosaic")) { install.packages("mosaic") }; library("mosaic")
#if(!require("cowplot")) { install.packages("cowplot") }; library("cowplot")
#if(!require("lavaan")) { install.packages("lavaan") }; library("lavaan")
#if(!require("fastDummies")) { install.packages("fastDummies") }; library("fastDummies")
#if(!require("lme4")) { install.packages("lme4") }; library("lme4")
#if(!require("lmerTest")) { install.packages("lmerTest") }; library("lmerTest")
#if(!require("rvest")) { install.packages("rvest") }; library("rvest")
if(!require("webdriver")) { install.packages("webdriver") }; library("webdriver")
if(!require("jsonlite")) { install.packages("jsonlite") }; library("jsonlite")
if(!require("webdriver")) { install.packages("webdriver") }; library("webdriver")
if(!require("airtabler")) { install.packages("airtabler") }; library("airtabler")
if(!require("readr")) { install.packages("readr") }; library("readr")
if(!require("dplyr")) { install.packages("dplyr") }; library("dplyr")
if(!require("purrr")) { install.packages("purrr") }; library("purrr")
if(!require("jsonlite")) { install.packages("jsonlite") }; library("jsonlite")
if(!require("devtools")) { install.packages("devtools") }; library("devtools")
if (inherits(try(run_phantomjs()), "try-error")) webdriver::install_phantomjs()
#if(!require("shiny")) { install.packages("shiny") }; library("shiny")
#if(!require("shinydashboard")) { install.packages("shinydashboard") }; library("shinydashboard")

#####################################################



